### ISSUE TITLE
2019 Shandong University AI Challenge

### ISSUE THREAD

**Issue by xinase** [microsoft/ai-edu#141]
2019年春季 山东大学《信息社会与人工智能》创新创业教育课程作业。 
作业要求在这里：
    https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/ShandongUniversity2019Spring 
请学生们把你的作业链接 （应该指向你的github 账户中的一个markdown 文件）回复到这个 Issue 下面即可。

**Comment by Imagetiger** [comment]
如何切换博客园编辑器为MarkDown？需要申请开通博客么

**Comment by TurborZhang** [comment]
https://github.com/TurborZhang/-/blob/master/201720121204

**Comment by LucieYutou** [comment]
https://github.com/LucieYutou/--/blob/master/201700081030.md

**Comment by baozansheng** [comment]
https://github.com/baozansheng/-/blob/master/201700031023.md/201700031023.md

**Comment by annyonly** [comment]
https://github.com/annyonly/demo/blob/master/201700082015.md.md

**Comment by lke0507** [comment]
[https://github.com/lke0507/201700082011.md/blob/master/201700082011.md](url)

**Comment by lke0507** [comment]
https://github.com/lke0507/201700082011.md/blob/master/201700082011.md

**Comment by AreYouKawaii** [comment]
https://github.com/AreYouKawaii/201700032022.md.git

**Comment by JPGD** [comment]
https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/ShandongUniversity2019Spring

**Comment by annyonly** [comment]
https://github.com/Gannaonly/201816080011.md/commit/2aae7e34f9a9285fcf9aaa4ee47c11622da6cff4

**Comment by Gannaonly** [comment]
https://github.com/Gannaonly/201816080011.md/blob/master/201716080011.md.md

**Comment by JPGD** [comment]
https://github.com/JPGD/201700032028/blob/master/201700032028.md

**Comment by yangyuanyuan1015** [comment]
https://github.com/yangyuanyuan1015/-/blob/master/201700031015.md

**Comment by luguohuan** [comment]
**https://github.com/luguohuan/201700032017/blob/master/201700032017.md**

**Comment by yikouchunzhen** [comment]
https://github.com/yikouchunzhen/201700301207

**Comment by yikouchunzhen** [comment]
https://github.com/yikouchunzhen/201700301207/blob/master/201700301207.md

**Comment by Doublesherry** [comment]
https://github.com/Doublesherry/DOUBLE/blob/master/201700081009.md

**Comment by robinn444** [comment]
https://github.com/robinn444/201720032066/blob/master/201702032066.md

**Comment by SUNNYCANDY** [comment]
https://github.com/SUNNYCANDY/201800020079/blob/master/README.md

**Comment by Happy2Y** [comment]
https://github.com/Happy2Y/201700073006.md.git

**Comment by 1T0T1** [comment]
https://github.com/1T0T1/3/blob/master/201700121076.md

**Comment by smin1014** [comment]
https://github.com/smin1014/demo/blob/master/201716080010.md.md

**Comment by dongyifan1999** [comment]
https://github.com/dongyifan1999/-.git

**Comment by dongyifan1999** [comment]
https://github.com/dongyifan1999/-.git

**Comment by dongyifan1999** [comment]
https://github.com/dongyifan1999/-.git

**Comment by dongyifan1999** [comment]
https://github.com/dongyifan1999/-.git

**Comment by sduliyi** [comment]
https://github.com/sduliyi/1111/blob/master/201700081014.md

**Comment by annyonly** [comment]
https://github.com/annyonly/demo/blob/master/201700082015.md.md

**Comment by Gannaonly** [comment]
https://github.com/Gannaonly/201816080011.md/blob/master/201726080011.md.md

**Comment by coco9946** [comment]
https://github.com/coco9946/201720071127.md.git

**Comment by KaylaChou** [comment]
https://github.com/KaylaChou/201700073007.md.git

**Comment by kkrs144** [comment]
https://github.com/kkrs144/201605261107.git

**Comment by kkrs144** [comment]
https://github.com/kkrs144/201605261107.git

**Comment by zqm990102** [comment]
https://github.com/zqm990102/201700081008/blob/master/201700081008.md

**Comment by xiuchengli** [comment]
https://github.com/xiuchengli/xiucheng.git

**Comment by Imagetiger** [comment]
https://github.com/Imagetiger/TIGER/blob/master/201718162252.md

**Comment by LownloadING** [comment]
https://github.com/LownloadING/demo

**Comment by WWQ1998** [comment]
https://github.com/WWQ1998/201700073015.md/blob/master/README.md

**Comment by jch140411** [comment]
demo /201700402007.md

**Comment by jch140411** [comment]
https://github.com/jch140411/demo/blob/34d715bb67cd2b3068172a2101eb23f36b76dd05/201700402007.md

**Comment by jch140411** [comment]
https://github.com/jch140411/demo/blob/a/201700402007.md

**Comment by lllllluxiao** [comment]
https://github.com/lllllluxiao/201700072016-.git

**Comment by 931801164** [comment]
https://github.com/931801164/-

**Comment by 931801164** [comment]
https://github.com/931801164/-/blob/master/README.md

**Comment by Inorst** [comment]
https://github.com/Inorst/Assignment/blob/master/201705100106.md

**Comment by diaolijie** [comment]
https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/ShandongUniversity2019Spring

**Comment by diaolijie** [comment]
https://github.com/diaolijie/201700121085.md/blob/master/201700121085.md

**Comment by lyhhhhhhhh** [comment]
https://github.com/lyhhhhhhhh/201700074027/blob/master/201700074027.md

**Comment by Elizabethmch** [comment]
> 2019年春季 山东大学《信息社会与人工智能》创新创业教育课程作业。
> 作业要求在这里：
> https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/ShandongUniversity2019Spring
> 请学生们把你的作业链接 （应该指向你的github 账户中的一个markdown 文件）回复到这个 Issue 下面即可。

https://github.com/Elizabethmch/201700171042.md/blob/master/201700171042.md

**Comment by liyangjian** [comment]
https://github.com/liyangjian/201700072020

**Comment by CyniHan** [comment]
https://github.com/CyniHan/homework/blob/master/201822273028.md

**Comment by WSXfunsun2019** [comment]
https://github.com/WSXfunsun2019/test/blob/master/file1/201700122033.md

**Comment by kabuqinuo555** [comment]
https://github.com/kabuqinuo555/201700121043/blob/master/201700121043.md

**Comment by jch140411** [comment]
https://github.com/jch140411/sgh/new/master

**Comment by jch140411** [comment]
https://github.com/jch140411/sgh/commit/073a2166cff4beed9bfeb02d69c8f32e5c0b5cff

**Comment by jch140411** [comment]
https://github.com/jch140411/sgh/commit/073a2166cff4beed9bfeb02d69c8f32e5c0b5cff

**Comment by QAQ516284797** [comment]
https://github.com/QAQ516284797/516284797/blob/master/201700301316.md

**Comment by Truongbin** [comment]
https://github.com/Truongbin/Truongbin/blob/master/201700031001.md

**Comment by JunyuWang6506** [comment]
https://github.com/JunyuWang6506/Wangjunyu/blob/master/201700031010.md

**Comment by leaplyly** [comment]
https://github.com/leaplyly/201700073020.md/blob/master/README.md

**Comment by Wanghaining1115** [comment]
https://github.com/Wanghaining1115/-/blob/master/201700031019.md/201700031019.md

**Comment by YUANYUAN9748** [comment]
https://github.com/YUANYUAN9748/ai-homework1/blob/master/201700081013.md

**Comment by jackliuibin** [comment]
https://github.com/jackliuibin/ai_class_homework/blob/master/201700301197.md

**Comment by GWSM** [comment]
https://www.cnblogs.com/gswm/p/10647422.htm

**Comment by liuyuezhaoming** [comment]
https://github.com/liuyuezhaoming/201700081006/blob/master/%E4%BD%9C%E4%B8%9A

**Comment by GWSM** [comment]
https://github.com/GWSM/201701082032

**Comment by GWSM** [comment]
https://github.com/GWSM/201701082032.md

**Comment by JenniferKikiTan** [comment]
https://github.com/JenniferKikiTan/201700071012/new/master?readme=1

**Comment by mig29y** [comment]
https://github.com/mig29y/201722121208/blob/master/201722121208.md

**Comment by ZzAeZhanG** [comment]
https://github.com/ZzAeZhanG/201500122021/commit/d46724c700581198b548fb77c765790ab756bda7

**Comment by ZzAeZhanG** [comment]
https://github.com/ZzAeZhanG/201500122021/commit/d46724c700581198b548fb77c765790ab756bda7

**Comment by ZzAeZhanG** [comment]
https://github.com/ZzAeZhanG/Homework/blob/master/201500122021.md

**Comment by yaqi0304** [comment]
https://github.com/yaqi0304/201700121012/edit/master/201700121012.md

**Comment by JenniferKikiTan** [comment]
https://github.com/JenniferKikiTan/T201700071012/blob/201700071012/201700071012.md

**Comment by 912559592** [comment]
https://github.com/912559592/yuhaoyu/blob/master/201700082021

**Comment by YXCM111** [comment]
https://github.com/YXCM111/201701082033.md

**Comment by GWSM** [comment]
https://github.com/GWSM/201701082032.md

**Comment by GWSM** [comment]
https://github.com/GWSM/201701082032.md

**Comment by Papacyliu** [comment]
https://github.com/Papacyliu/liuyutong1/blob/master/201700031038.md

**Comment by JunoShi** [comment]
https://github.com/JunoShi/tiantingshi/blob/master/201700031003.md

**Comment by finnambenben** [comment]
https://github.com/finnambenben/repo/blob/master/201700031047.md/201700031047.md

**Comment by fubowenfu** [comment]
https://github.com/fubowenfu/fubowenfu/blob/master/201700121153

**Comment by fubowenfu** [comment]
https://github.com/fubowenfu/fubowenfu/blob/master/201700121153.md

**Comment by weigui145** [comment]
https://github.com/weigui145/201700273021/blob/master/201700273021.md

**Comment by youngleeli** [comment]
https://github.com/youngleeli/-/blob/master/201700031046.md/201700031046.md

**Comment by GuardV** [comment]
> 2019年春季 山东大学《信息社会与人工智能》创新创业教育课程作业。
> 作业要求在这里：
> https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/ShandongUniversity2019Spring
> 请学生们把你的作业链接 （应该指向你的github 账户中的一个markdown 文件）回复到这个 Issue 下面即可。
https://github.com/GuardV/201600112035/blob/master/201600112035

**Comment by lznlj** [comment]
https://github.com/lznlj/201700082025/blob/master/201700082025.rnd

**Comment by yikoulaoguo** [comment]
https://github.com/yikoulaoguo/Demo/blob/master/201700073024.md

**Comment by LUXIAOYANGLXY** [comment]
https://github.com/LUXIAOYANGLXY/blob/blob/master/README.md/201700302050.md

**Comment by WCJ1234567890** [comment]
https://github.com/WCJ1234567890/201700072014/blob/master/README.md

**Comment by heyingze** [comment]
https://github.com/heyingze/201700072018.-.git

**Comment by C1999ztzt** [comment]
https://github.com/C1999ztzt/201700190035.md/blob/master/homework

**Comment by yinshenqi** [comment]
https://github.com/yinshenqi/alghhigi/blob/master/201700071045.md

**Comment by QIUQIUHAO** [comment]
https://github.com/QIUQIUHAO/-/blob/master/201700031009.md

**Comment by Leoxf** [comment]
https://github.com/Leoxf/Leoxf/blob/master/201700031050.md

**Comment by Leoxf** [comment]
https://github.com/Leoxf/Leoxf/blob/master/201700031050.md

**Comment by vlayy** [comment]
https://github.com/vlayy/201700072017/blob/master/README.md

**Comment by jackliu998** [comment]
https://github.com/jackliu998/201700271217.md

**Comment by 201700301114huapei** [comment]
https://github.com/201700301114huapei/demo/blob/master/201700301114.md

**Comment by ZGS9943** [comment]
https://github.com/ZGS9943/201700262017/wiki

**Comment by OOMichaelOO** [comment]
https://github.com/OOMichaelOO/Demo/blob/master/201700301007.md

**Comment by cirensangji** [comment]
https://github.com/cirensangji/201701082034.md

**Comment by cirensangji** [comment]
https://github.com/cirensangji/201701082034.md

**Comment by huicongyang** [comment]
https://github.com/huicongyang/sb/blob/master/201700031020.md

**Comment by LiXP91** [comment]
https://github.com/LiXP91/201700121094/blob/master/homework/201700121094.md

**Comment by Yong153489** [comment]
https://github.com/Yong153489/201701082036.md

**Comment by Backspace98** [comment]
https://github.com/Backspace98/201700073012.md.git

**Comment by WCTISGOD** [comment]
https://github.com/WCTISGOD/201700121025.md/new/master

**Comment by WCTISGOD** [comment]
https://github.com/WCTISGOD/201700121025.md/tree/master

**Comment by Antoni1111111** [comment]
https://github.com/Antoni1111111/201700071021.md/tree/master

**Comment by lvyougang** [comment]
> 2019年春季山东大学“信息社会与人工智能”创新创业教育课程作业。
> 作业要求在这里：
> [https](https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/ShandongUniversity2019Spring)：[//github.com/Microsoft/ai-edu/tree/master/E-Challenge/ShandongUniversity2019Spring](https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/ShandongUniversity2019Spring)
> 请学生们把你的作业链接（应该指向你的github上账户中的一个降价文件）回复到这个问题下面即可。

https://github.com/lvyougang/hello-git-hub/blob/master/201700072025.md

**Comment by lvyougang** [comment]
https://github.com/lvyougang/hello-git-hub/blob/master/201700072025.md

**Comment by chinajapankorea** [comment]
https://github.com/chinajapankorea/dragon/blob/master/201700121016.md

**Comment by Tanialin** [comment]
https://github.com/Tanialin/201700032033/blob/master/201700032033.md

**Comment by FloraRobyn** [comment]
https://github.com/FloraRobyn/201700073009.md/tree/master

**Comment by FloraRobyn** [comment]
https://github.com/FloraRobyn/201700073009.md/tree/master

**Comment by FloraRobyn** [comment]
https://github.com/FloraRobyn/201700073009.md/tree/master

**Comment by f1473674014** [comment]
https://github.com/f1473674014/201718121191.md/blob/master/201718121191.md

**Comment by HKhql** [comment]
https://github.com/HKhql/201600202120.md/blob/master/201600202120.md

**Comment by 931801164** [comment]
https://github.com/931801164/-201700402009/blob/master/README.md

**Comment by tiantian328** [comment]
https://github.com/tiantian328/201700082001.md.git

**Comment by crazier40** [comment]
https://github.com/crazier40/201718121181.md/blob/master/201718121181.md

**Comment by YingOlivia** [comment]
https://github.com/YingOlivia/Believe-myself.git

**Comment by YingOlivia** [comment]
https://github.com/YingOlivia/Believe-myself/blob/00cf69630c50cf8669e356972834da208785c335/201700271173.md

**Comment by Penghuanqaz** [comment]
https://github.com/Penghuanqaz/Penghuan/blob/master/README.md

**Comment by popoyee** [comment]
https://github.com/popoyee/201700071047.md/commit/1818d865ba8f52cb6c1004bcbc5755cbfa4eb55d

**Comment by Lois-Jacky** [comment]
https://github.com/Lois-Jacky/201700081012.md/blob/master/homework

**Comment by tiantian328** [comment]
https://github.com/tiantian328/201700082001.md/find/master

**Comment by tiantian328** [comment]
https://github.com/tiantian328/201700082001.md/blob/master/201700082001.md

**Comment by Sarasotanise** [comment]
https://github.com/Sarasotanise/201722031055.md/new/master

**Comment by Sarasotanise** [comment]
https://github.com/Sarasotanise/201722031055.md/blob/master/Review

**Comment by sunshine0104** [comment]
https://github.com/sunshine0104/201700301263.md

**Comment by ccwh** [comment]
https://github.com/ccwh/MS_homework/blob/master/201600100060.md

**Comment by xuyixin123** [comment]
https://github.com/Microsoft/ai-edu/compare/master...xuyixin123:patch-1

**Comment by xuyixin123** [comment]
https://github.com/Microsoft/ai-edu/compare/master...xuyixin123:patch-1

**Comment by Wanghaining1115** [comment]
https://github.com/Microsoft/ai-edu/compare/master...Wanghaining1115:patch-1

**Comment by yangyananasteria** [comment]
https://github.com/yangyananasteria/201700071038.md.git

**Comment by AZZ233** [comment]
https://github.com/AZZ233/201700100082.md.git

**Comment by Techmessager** [comment]
https://github.com/Techmessager/test/blob/master/201700301143.md

**Comment by ningzichun** [comment]
https://github.com/ningzichun/sduhw/blob/master/201800190216.md

**Comment by liyangjian** [comment]
https://github.com/liyangjian/201700100080/blob/master/201700100080.md

**Comment by angelakit** [comment]
> 2019年春季 山东大学《信息社会与人工智能》创新创业教育课程作业。
> 作业要求在这里：
> https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/ShandongUniversity2019Spring
> 请学生们把你的作业链接 （应该指向你的github 账户中的一个markdown 文件）回复到这个 Issue 下面即可。

test2017/file1/201700121040.md

**Comment by angelakit** [comment]
test2017/file1/201700121040.md

**Comment by angelakit** [comment]
https://github.com/angelakit/test2017/blob/master/file1/201700121040.md

**Comment by sunlishuang** [comment]
https://github.com/sunlishuang/sunlishuang/blob/master/201700032002.md

**Comment by Verameng7** [comment]
https://github.com/Verameng7/201700121080.md/commit/cd04318559e98bc47b99ad8974b7e2366741a62b

**Comment by Verameng7** [comment]
https://github.com/Verameng7/201700121080.md/commit/cd04318559e98bc47b99ad8974b7e2366741a62b

**Comment by Verameng7** [comment]
https://github.com/Verameng7/201700121080.md/commit/cd04318559e98bc47b99ad8974b7e2366741a62b

**Comment by lxr99** [comment]
https://github.com/lxr99/201700121082.md.git

**Comment by LUOXIAOLANLAN** [comment]
https://github.com/LUOXIAOLANLAN/201718121189.md.git

**Comment by nxc736388548** [comment]
https://github.com/nxc736388548/201700072024.md/tree/master

**Comment by liuchen1231** [comment]
https://github.com/liuchen1231/201700072026.md/tree/master

**Comment by ximuziyee** [comment]
https://github.com/ximuziyee/201700071047.md/tree/master

**Comment by ximuziyee** [comment]
https://github.com/ximuziyee/201700071047.md/tree/master

**Comment by ximuziyee** [comment]
https://github.com/ximuziyee/201700071047.md/blob/master/201700071047.md

**Comment by zoushuangshuang** [comment]
E-Challenge/ShandongUniversity2019Spring/201700031048.md

**Comment by zoushuangshuang** [comment]
https://github.com/Microsoft/ai-edu/compare/master...zoushuangshuang:patch-2

**Comment by CandyLSJ** [comment]
https://github.com/CandyLSJ/201700121156.md

**Comment by CandyLSJ** [comment]
https://github.com/CandyLSJ/201700121156.md/blob/master/%E4%BF%A1%E6%81%AF%E7%A4%BE%E4%BC%9A%E4%B8%8E%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD3

**Comment by CandyLSJ** [comment]
https://github.com/CandyLSJ/201700121156.md/blob/master/%E4%BF%A1%E6%81%AF%E7%A4%BE%E4%BC%9A%E4%B8%8E%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD3

**Comment by CandyLSJ** [comment]
https://github.com/CandyLSJ/201700121156.mdx.git

**Comment by CandyLSJ** [comment]
https://github.com/CandyLSJ/201700121156.md/blob/master/three

**Comment by Yu00112** [comment]
https://github.com/Yu00112/201700121067.md/blob/master/201700121067

**Comment by Yu00112** [comment]
https://github.com/Yu00112/201700121067.md/blob/master/201700121067

**Comment by Yu00112** [comment]
https://github.com/Yu00112/201700121067.md/blob/master/201700121067

**Comment by Yu00112** [comment]
https://github.com/Yu00112/201700121067.md/blob/master/201700121067

**Comment by Yu00112** [comment]
https://github.com/Yu00112/201700121067.md/blob/master/201700121067

**Comment by Yu00112** [comment]
https://github.com/Yu00112/201700121067.md/blob/master/201700121067

**Comment by Yu00112** [comment]
https://github.com/Yu00112/201700121067.md/blob/master/201700121067

**Comment by Yu00112** [comment]
https://github.com/Yu00112/201700121067.md/blob/master/201700121067

**Comment by zzzzjj** [comment]
https://github.com/zzzzjj/201701121162.md/blob/master/201701121162.md

**Comment by 2227567099** [comment]
https://github.com/2227567099/201718121188.md/blob/master/201718121188.md

**Comment by Xiaomianxiaowanzi** [comment]
https://github.com/Xiaomianxiaowanzi/201718121190.md/tree/master

**Comment by muqiyuning** [comment]
https://github.com/muqiyuning/201718121170.md/blob/master/201718121170.md

**Comment by muqiyuning** [comment]
https://github.com/muqiyuning/201718121170.md/blob/master/201718121170.md

**Comment by SukYt** [comment]
https://github.com/SukYt/-201700071001.md

**Comment by SDU-YH** [comment]
https://github.com/SDU-YH/demo/blob/master/201700301297.md

**Comment by SDU-YH** [comment]
https://github.com/SDU-YH/demo/blob/master/201700301297.md

**Comment by tiantianguoguo** [comment]
https://github.com/tiantianguoguo/-/blob/master/201700121031.md

**Comment by zhanghoy** [comment]
https://github.com/zhanghoy/zhanghoy/blob/master/201700031039.md

**Comment by ambercrane** [comment]
https://github.com/ambercrane/201800271017.md/blob/master/201800271017.md

**Comment by sunshine0104** [comment]
https://github.com/sunshine0104/201700301263.md/tree/master

**Comment by zhouleibin** [comment]
https://github.com/zhouleibin/201700121128.md/blob/master/201700121128.md

**Comment by xinase** [comment]
> https://github.com/zhouleibin/201700121128.md/blob/master/201700121128.md

N（需求）部分大学生沉迷网络，意志不坚定，有时不自觉的浪费时间，想学习又没有动力，懒得动，需要些激励。

是你认为他们需要激励，  还是他们认为他们自己需要激励？

**Comment by xinase** [comment]
> https://github.com/sunshine0104/201700301263.md/tree/master

>app能够专门记录分享各地的旅游攻略那该有多好啊
这样的APP 已经有不少了呀， 连高德地图这样的app 都可以搜各种当地旅游资源了。 请用一下。

**Comment by xinase** [comment]
> https://github.com/ambercrane/201800271017.md/blob/master/201800271017.md

> 可以开发一个识别植物种类并科普植物特点的app.
这样的App 和微信小程序已经很多了， 你没有用过么？

**Comment by xinase** [comment]
> https://github.com/tiantianguoguo/-/blob/master/201700121031.md

> 在改变选择之前概率为1/3，之后为1/2，所以提高了，提高了1/6.
这个不对， 请仔细考虑。

**Comment by chenzhiwei888** [comment]
https://github.com/chenzhiwei888/201720121196.md/blob/master/201720121196

**Comment by zhanghoy** [comment]
https://github.com/zhanghoy/blob/master/201700031039.md

**Comment by sunshine0104** [comment]
https://github.com/sunshine0104/201700301263.md/blob/master/my%20first%20homework

**Comment by LUXIAOYANGLXY** [comment]
https://github.com/LUXIAOYANGLXY/blob/blob/master/README.md/201700302050.md

**Comment by zhanghoy** [comment]
https://github.com/zhanghoy/201700031039/blob/master/201700031039.md

**Comment by cpfKKKK** [comment]
https://github.com/cpfKKKK/cpf/blob/master/201700301338.md

**Comment by zhanghoy** [comment]
https://github.com/zhanghoy/201700031039zhanghongyang

**Comment by zhanghoy** [comment]
https://github.com/zhanghoy/201700031039zhanghongyang/blob/master/README.md

**Comment by GHJ1999** [comment]
https://github.com/GHJ1999/201700032039.md/blob/master/201700032039

**Comment by chenzhiwei888** [comment]
https://github.com/chenzhiwei888/201720121196.md/create/master

**Comment by chenzhiwei888** [comment]
https://github.com/chenzhiwei888/201720121196.md/create/master/201720121196

**Comment by chenzhiwei888** [comment]
https://github.com/chenzhiwei888/201720121196.md/blob/master/201720121196.md

**Comment by NingningTao** [comment]
https://github.com/NingningTao/201518121235.md/blob/master/201518121235.md

**Comment by 201700032027** [comment]
https://github.com/201700032027/diaodiao/tree/master

**Comment by 201700032027** [comment]
https://github.com/201700032027/diaodiao/blob/master/201700032027.md

**Comment by asansan** [comment]
https://github.com/asansan/201718121183.md/blob/master/201718121183.md

**Comment by zhaoxingyun99** [comment]
https://github.com/zhaoxingyun99/201700121083.mmm/blob/master/201700121083

**Comment by zhaoxingyun99** [comment]
https://github.com/zhaoxingyun99/201700121083.mmm/blob/master/201700121083.md

**Comment by zhangxuguang1** [comment]
https://github.com/zhangxuguang1/201700121125/blob/master/201700121125.md

**Comment by Tanialin** [comment]
https://github.com/Tanialin/Jinglin201700032033/blob/master/201700032033.md

**Comment by renshuchang125** [comment]
https://github.com/renshuchang125/201700031029/blob/master/201700031029.md

**Comment by ccjq** [comment]
https://github.com/ccjq/1/blob/master/201700031011.md.md

**Comment by KawayiWen** [comment]
https://github.com/KawayiWen/W201700071011/blob/master/201700071011.md

**Comment by YangYang2525** [comment]
https://github.com/YangYang2525/201700073029.md/blob/master/README.md

**Comment by FeiLuoRan** [comment]
https://github.com/FeiLuoRan/demo/commit/e32234052275daa7a86b2b3fd1606522855f54ac

**Comment by daizhaocun** [comment]
https://github.com/daizhaocun/201700121084.md

**Comment by blingbonnie** [comment]
https://github.com/blingbonnie/201700073032/blob/master/201700073032.md

**Comment by SylviaEPang** [comment]
https://github.com/SylviaEPang/201700121105.md/tree/master

**Comment by Hannah1999H** [comment]
https://github.com/Hannah1999H/201705071095/blob/master/201705071095.md

**Comment by rogerssong** [comment]
https://github.com/rogerssong/-.qzHMtv/blob/master/201700273018.md

**Comment by yuxinWYX** [comment]
https://github.com/yuxinWYX/homework/blob/c4499a274595125468e874b7851eb5e7b99e4fbd/201800020145.md

**Comment by 744391775** [comment]
https://github.com/744391775/shit/blob/master/201700121077.md

**Comment by xinase** [comment]
> https://github.com/744391775/shit/blob/master/201700121077.md

行李箱的电源问题如何解决呢？

**Comment by 2889692026** [comment]
https://github.com/2889692026/Markdown/blob/master/201700121023.md

**Comment by Hey-Sapling** [comment]
https://github.com/Hey-Sapling/201700071037.md.git

**Comment by BaiYanLi** [comment]
https://github.com/BaiYanLi/201700121126.md/blob/master/201700121126

**Comment by wangyilong1015** [comment]
https://github.com/wangyilong1015/201700121015.md/tree/master

**Comment by Flamingo59420** [comment]
https://github.com/Flamingo59420/homework/blob/master/201718121186.md

**Comment by Flamingo59420** [comment]
https://github.com/Flamingo59420/homework/blob/master/201718121186.md

**Comment by Flamingo59420** [comment]
https://github.com/Flamingo59420/homework/blob/master/201718121186.md

**Comment by Flamingo59420** [comment]
https://github.com/Flamingo59420/homework/blob/master/201718121186.md

**Comment by Flamingo59420** [comment]
https://github.com/Flamingo59420/homework/blob/master/201718121186.md

**Comment by Flamingo59420** [comment]
https://github.com/Flamingo59420/homework/blob/master/201718121186.md

**Comment by Flamingo59420** [comment]
https://github.com/Flamingo59420/homework/blob/master/201718121186.md

**Comment by Flamingo59420** [comment]
https://github.com/Flamingo59420/homework/blob/master/201718121186.md

**Comment by Flamingo59420** [comment]
https://github.com/Flamingo59420/homework/blob/master/201718121186.md

**Comment by AmbitiousXH** [comment]
https://github.com/AmbitiousXH/AIchallenge/blob/master/201700122068.md

**Comment by AmbitiousXH** [comment]
https://github.com/AmbitiousXH/AIchallenge/blob/master/201700122068.md

**Comment by SJP677** [comment]
https://github.com/SJP677/201700121089.md/blob/master/201700121089.md

**Comment by wubian201700121030** [comment]
https://github.com/wubian201700121030/201700121030/commits?author=wubian201700121030

**Comment by wubian201700121030** [comment]
https://github.com/wubian201700121030/201700121030/commits?author=wubian201700121030

**Comment by wubian201700121030** [comment]
https://github.com/wubian201700121030/201700121030/commits?author=wubian201700121030

**Comment by wubian201700121030** [comment]
https://github.com/wubian201700121030/201700121030/commits?author=wubian201700121030

**Comment by guoruiyu** [comment]
https://github.com/guoruiyu/201720121194.md/blob/master/201720121194.md

**Comment by Carolisme1** [comment]
https://github.com/Carolisme1/201700073026.git

**Comment by liuzhensdu** [comment]
https://github.com/liuzhensdu/liuzhen/blob/master/201700121102

**Comment by llliming** [comment]
https://github.com/llliming/201700121133/blob/master/201700121133.md

**Comment by Tanjiuer** [comment]
https://github.com/Tanjiuer/kechengzuoye/blob/master/201700140091

**Comment by dongyifan1999** [comment]
https://github.com/dongyifan1999/201800271099-md.git

**Comment by Lucia34** [comment]
https://github.com/Lucia34/ok34/tree/master

**Comment by bmc666** [comment]
https://github.com/bmc666/GitHub/blob/master/201700121018.md

**Comment by wz1437047753** [comment]
https://github.com/wz1437047753/wz1437047753/blob/master/201700121017.md

**Comment by wboommmmm** [comment]
https://github.com/wboommmmm/201700082024/blob/master/201700082024.md

**Comment by wanghanhh** [comment]
https://github.com/wanghanhh/201700121062/blob/master/201700121062

**Comment by 1243868898** [comment]
https://raw.githubusercontent.com/1243868898/201700121114.md/master/201700121114.md

**Comment by LeBronhan** [comment]
https://github.com/LeBronhan/201700121138.md/blob/master/201700121138.md

**Comment by Crystal626256549** [comment]
> 2019年春季 山东大学《信息社会与人工智能》创新创业教育课程作业。
> 作业要求在这里：
> https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/ShandongUniversity2019Spring
> 请学生们把你的作业链接 （应该指向你的github 账户中的一个markdown 文件）回复到这个 Issue 下面即可。

https://github.com/Crystal626256549/201700122052/blob/master/201700122052.md

**Comment by hayley199903023** [comment]
https://github.com/hayley199903023/201700210044/blob/master/201700210044.md

**Comment by Cecilia990818** [comment]
https://github.com/Cecilia990818/201700079006/blob/master/201700079006.md

**Comment by mslichao** [comment]
#173 #179 #181 #188 #194 #195 #196 #197 #240 #243
may belong this challenge too, close them due to the wrong reply format.
