### ISSUE TITLE
2019年春季 北航《计算机科学前沿》挑战

### ISSUE THREAD

**Issue by xinase** [microsoft/ai-edu#154]
**2019年春季 北航《计算机科学前沿》挑战**
作业要求在这里：
https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/BeihangUniversity2019Spring 

请北航的学生们把你的作业链接 （应该指向你的 github 账户中的一个markdown 文件）回复到这个 Issue 下面即可。

**Comment by butub1** [comment]
https://github.com/butub1/Lecture/blob/master/16061048.md

**Comment by wxmwy** [comment]
https://github.com/wxmwy/2019-/blob/master/16061156.md

**Comment by lvba** [comment]
https://github.com/lvba/homework/blob/master/16061056.md

**Comment by Heyedanlty** [comment]
https://github.com/Heyedanlty/BUAA_2019_LECTURE_HomeworkPlus/blob/master/16231256.md

**Comment by pan-x-c** [comment]
https://github.com/pan-x-c/FrontierLecture2019Spring/blob/master/16061059.md

**Comment by drmeerkat** [comment]
https://github.com/drmeerkat/ML-Talk-Assignments/blob/master/assignment.md

**Comment by Acloud11** [comment]
https://github.com/Acloud11/buaa_-Frontier-of-Computer-Science_homework/blob/master/16061046.md

**Comment by Changy1506** [comment]
https://github.com/Changy1506/homework/blob/master/15061149.md

**Comment by byby221b** [comment]
https://github.com/byby221b/Homework/blob/master/16061098.md
（白勇 16061098）

**Comment by supplient** [comment]
https://github.com/supplient/lecture_homework/blob/master/16061103.md

**Comment by wjy121388** [comment]
https://github.com/wjy121388/LectureHomework/blob/master/16061071.md

**Comment by jy0205** [comment]
https://github.com/jy0205/HomwWork/blob/master/16061088.md

**Comment by fondoger** [comment]
https://gist.github.com/fondoger/731a303bc9dc05b59fd178c8a5f9a608

**Comment by MaybeSilent** [comment]
https://github.com/MaybeSilent/homework/blob/master/homework.md

**Comment by wenguang1998** [comment]
https://github.com/wenguang1998/2019_spring_CS_homework/blob/master/16061069.md

**Comment by zhysora** [comment]
https://github.com/zhysora/ai-edu/blob/master/E-Challenge/BeihangUniversity2019Spring/16061052.md

**Comment by entarromsf** [comment]
https://github.com/entarromsf/lecture/blob/master/16231046.md

**Comment by captgao** [comment]
https://github.com/captgao/Lecture/blob/master/15271124.md

**Comment by Stevring** [comment]
https://github.com/Stevring/InformalEssays/blob/master/2019Spring%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%A7%91%E5%AD%A6%E5%89%8D%E6%B2%BF/16061143.md

**Comment by BigaGrayWolf** [comment]
https://github.com/BigaGrayWolf/15061191/blob/master/15061191.md

**Comment by mingming97** [comment]
https://github.com/mingming97/ai-edu-2019/blob/master/16061131.md

**Comment by xiaobichen** [comment]
https://github.com/xiaobichen/homework1/blob/master/16061001.md

**Comment by Welkin1027** [comment]
https://github.com/Welkin1027/CS_Homework/blob/master/16061197.md

**Comment by jiazhengniu** [comment]
https://github.com/jiazhengniu/demo/blob/master/16061039.md

**Comment by Chen-Qixian** [comment]
https://github.com/Chen-Qixian/BUAA-Lecture/blob/master/16061160.md

**Comment by wpy16131034** [comment]
https://github.com/wpy16131034/homework/blob/master/16131034.md

**Comment by shawnco411** [comment]
https://github.com/shawnco411/BUAA_LECTURE/blob/master/15005030.md

**Comment by RookieFanzk** [comment]
https://github.com/RookieFanzk/Lecture_homework/blob/master/16061051.md

**Comment by lsj2408** [comment]
https://github.com/lsj2408/CS_Lecture_HW/16081099.md

**Comment by KeXiangWang** [comment]
https://github.com/KeXiangWang/Microsoft-ai-edu-homework/blob/master/homework.md

**Comment by XHQvi** [comment]
https://github.com/XHQvi/document/blob/master/16061138.md

**Comment by Eins0** [comment]
https://github.com/Eins0/Microsoft_ai_edu_HW/blob/master/HomeWork.md

**Comment by Eins0** [comment]
https://github.com/Eins0/Microsoft_ai_edu_HW/blob/master/HomeWork.md

**Comment by Eins0** [comment]
https://github.com/Eins0/Microsoft_ai_edu_HW/blob/master/16061124_HomeWork.md

**Comment by JamesDYX** [comment]
https://github.com/JamesDYX/FrontierComputerScienceLecture/blob/master/16061183.md

**Comment by hhjiayou** [comment]
https://github.com/hhjiayou/16182646.md/blob/master/16182646.md

**Comment by Ifpeng** [comment]
https://github.com/Ifpeng/FrontierLectureOfDiscipline2019/blob/master/16061110.md

**Comment by MyLife97** [comment]
https://github.com/MyLife97/Academic_Lecture/blob/master/15071054.md

**Comment by yqmmm** [comment]
https://github.com/yqmmm/CSFrontier2019Spring/blob/master/15131079.md

**Comment by t68i663** [comment]
https://github.com/t68i663/lecture_homework/blob/master/16061006.md

**Comment by ghostezhouxingyu** [comment]
https://github.com/ghostezhouxingyu/2019springAIChallenge/blob/master/16061022.md

**Comment by asevergreen** [comment]
https://github.com/asevergreen/FrontierLecture2019Homework/blob/master/16061179.md

**Comment by YWGGG** [comment]
https://github.com/YWGGG/BUAA_2019_LECTURE_PLUS/blob/master/16061016.md

**Comment by maybetomorrow99** [comment]
https://github.com/maybetomorrow99/BUAA_Lecture/blob/master/16061028.md

**Comment by 171164558** [comment]
https://github.com/171164558/ai_homework/blob/master/16061158.md

**Comment by 171164558** [comment]
https://github.com/171164558/ai_homework/blob/master/16061158.md

**Comment by xurongxiang** [comment]
https://github.com/xurongxiang/homework/blob/master/16061047.md

**Comment by xiaoxin83121** [comment]
https://github.com/xiaoxin83121/FrontierLectures/blob/master/16061017.md

**Comment by ChieloNewctle** [comment]
https://github.com/ChieloNewctle/ai-edu-assignment/blob/master/16061187.md

**Comment by mio4** [comment]
https://github.com/mio4/FrontierComputerScienceLecture/blob/master/16061201.md

**Comment by XCX127** [comment]
https://github.com/XCX127/16182643/blob/master/16182643.md

**Comment by GaryNotGay** [comment]
https://github.com/GaryNotGay/Microsoft-BeihangUniversity2019Spring/blob/master/16182678.md

**Comment by kirito12138** [comment]
https://github.com/kirito12138/ai-edu-assignment/blob/master/16061173.md

**Comment by swearitagain** [comment]
https://github.com/swearitagain/ai-edu-assignment/blob/master/16061202.md

**Comment by Ignautics** [comment]
https://github.com/Ignautics/blob/blob/master/16061057.md

**Comment by JianbingWang** [comment]
https://github.com/JianbingWang/csforward/blob/master/16061165.md

**Comment by landNo7** [comment]
https://github.com/landNo7/ai-edu-2019/blob/master/16061084.md

**Comment by 66797110** [comment]
https://github.com/66797110/BUAA_2019_ai-edu/blob/master/16182677.md

**Comment by HullQin** [comment]
https://github.com/HullQin/Microsoft-ai-edu-tree-E-Challenge/blob/master/15091051.md

**Comment by Cookize** [comment]
https://github.com/Cookize/ai_edu_homework/blob/master/16061170.md

**Comment by 16061025** [comment]
https://github.com/16061025/Micro_BUAA_Lecture/blob/master/16061025.md

**Comment by swordpj** [comment]
https://github.com/swordpj/Homework/blob/master/16061078.md

**Comment by canuse** [comment]
https://github.com/canuse/LectureHomework/blob/master/16061161.md

**Comment by waveliu98** [comment]
https://github.com/waveliu98/le_homework/blob/master/16061038.md

**Comment by wendingp** [comment]
https://github.com/wendingp/ai-edu-homework/blob/master/15241035.md

**Comment by Xuanxuan137** [comment]
https://github.com/Xuanxuan137/Buaa2019_Frontier_lectures_Homework/blob/master/16061043.md

**Comment by kenyin123** [comment]
https://github.com/kenyin123/ai-edu/blob/master/E-Challenge/BeihangUniversity2019Spring/16061190.md

**Comment by TemplaX** [comment]
https://github.com/TemplaX/Microsoft-Homework/blob/master/16061087.md

**Comment by shihaobai** [comment]
https://github.com/shihaobai/AI/blob/master/16061167.md

**Comment by KL-ice** [comment]
https://github.com/KL-ice/2019_buaa_lecture_homework/blob/master/16061155.md

**Comment by RickyZhang901** [comment]
https://github.com/RickyZhang901/LectureHomework/blob/master/16061126.md

**Comment by bwisme** [comment]
https://github.com/bwisme/Homework/blob/master/16091049.md

**Comment by paradoxtown** [comment]
https://github.com/paradoxtown/2019_buaa_lecture_homework/blob/master/16061162.md

**Comment by Dicky35** [comment]
https://github.com/Dicky35/lecture/blob/master/16061136.md

**Comment by Diralpo** [comment]
https://github.com/Diralpo/Homework/blob/master/ai-edu/16061107.md

**Comment by kilotron** [comment]
https://github.com/kilotron/ai-edu-E-Challenge-BeihangUniversity2019Spring/blob/master/16061200.md

**Comment by Niuyuhang03** [comment]
https://github.com/Niuyuhang03/BUAA_Lecture/blob/master/16061011.md

**Comment by Melina-Zh** [comment]
https://github.com/Melina-Zh/BUAA_lecture/blob/master/16061152.md

**Comment by Uchiha-ciel** [comment]
https://github.com/Uchiha-ciel/Homework/blob/master/ai-edu/16061113.md

**Comment by Mujt** [comment]
https://github.com/Mujt/Spring_lecture_homework/blob/master/16231173.md

**Comment by Groexhy** [comment]
https://github.com/Groexhy/homework_spring2019/blob/master/16061111.md

**Comment by 16061042** [comment]
https://github.com/16061042/homework/blob/master/16061042.md

**Comment by AirTaker** [comment]
https://github.com/AirTaker/Lecture/blob/master/16061141.md

**Comment by L-Richard** [comment]
https://github.com/L-Richard/Lecture2019/blob/master/15071111.md

**Comment by Challenging6** [comment]
https://github.com/Challenging6/BUAA-2019-Computer-Lecture-Homework/blob/master/16061079.md

**Comment by reynolds9808** [comment]
https://github.com/reynolds9808/FrontierLecture2019/blob/master/16061083.md

**Comment by MKibera** [comment]
https://github.com/MKibera/homework/blob/master/16061072.md

**Comment by tzhhhh123** [comment]
https://github.com/tzhhhh123/Homework/blob/master/16061085.md

**Comment by SongXiaoXi** [comment]
https://github.com/SongXiaoXi/BUAA-Al-edu-homework/blob/master/15071060.md

**Comment by lxqiaoyixuan** [comment]
https://github.com/lxqiaoyixuan/HomeWork2019spring/blob/master/16061062.md

**Comment by chuizi000** [comment]
https://github.com/chuizi000/homework/blob/master/16061144.md

**Comment by jump882** [comment]
https://github.com/jump882/homework/blob/master/16182644.md

**Comment by Null233** [comment]
https://github.com/Null233/2019-Lecture/blob/master/16061073.md

**Comment by renhouxing** [comment]
https://github.com/renhouxing/Homework/blob/master/15051096.md

**Comment by RookieCooder** [comment]
https://github.com/RookieCooder/homework/blob/master/16061101.md

**Comment by laudavid** [comment]
https://github.com/laudavid/blogs/blob/master/%E5%AD%A6%E7%A7%91%E6%8A%80%E6%9C%AF%E5%89%8D%E6%B2%BF%E8%AE%B2%E5%BA%A7/16061175.md

**Comment by ELFEamp** [comment]
https://github.com/ELFEamp/Lecture-Assignments/blob/master/Lecture-Assignments/16061116.md

**Comment by l2280212** [comment]
https://github.com/l2280212/homework/blob/master/16061090.md

**Comment by KurohaneNioko** [comment]
https://github.com/KurohaneNioko/MyTools/blob/master/16231246.md

**Comment by Yang-15** [comment]
https://github.com/Yang-15/Type-A/blob/master/16182676.md

**Comment by awfsgdf** [comment]
https://github.com/awfsgdf/lecture/blob/master/16061168.md

**Comment by JavieraStephanie** [comment]
https://github.com/JavieraStephanie/Beihang-University/blob/master/76066002.md

**Comment by JiuYueJiWang** [comment]
https://github.com/JiuYueJiWang/BUAA_Microsoft/blob/master/16061134.md

**Comment by yhwputin** [comment]
https://github.com/yhwputin/BUAA_homework/blob/master/16182614.md

**Comment by 11weioswald** [comment]
https://github.com/11weioswald/2019-.git/16182605.md

**Comment by 11weioswald** [comment]
https://github.com/11weioswald/2019-.git

**Comment by zhaxxxian** [comment]
https://github.com/zhaxxxian/buaa_homework/blob/master/16182613.md

**Comment by 7O11** [comment]
https://github.com/7O11/Lecture_2019/blob/master/15131002.md

**Comment by niyangge** [comment]
https://github.com/niyangge/Homework/blob/master/16182680.md

**Comment by NanonaN** [comment]
https://github.com/NanonaN/Lecture-homework/blob/master/16061125.md  
> 16061125 周雨飞

**Comment by 11weioswald** [comment]
https://github.com/11weioswald/2019-/blob/master/16182605.md

**Comment by ellewater** [comment]
https://github.com/ellewater/Academic-Lecture/blob/master/16061035.md

**Comment by yyfydtyxy** [comment]
https://github.com/yyfydtyxy/16061139/blob/master/16061139.md

**Comment by yyfydtyxy** [comment]
https://github.com/yyfydtyxy/16061139/blob/master/16061139.md

**Comment by woxiangquca** [comment]
https://github.com/woxiangquca/lecture/blob/master/16061117.md

**Comment by Dunnnnn** [comment]
https://github.com/Dunnnnn/Homework/blob/master/16231136.md

**Comment by jyqin1117** [comment]
https://github.com/jyqin1117/2019_FrontierLecture/blob/master/16061061.md

**Comment by ycl1035621458** [comment]
https://github.com/ycl1035621458/jiangzuo/blob/master/16061147.md

**Comment by lmjfmqsrc** [comment]
https://github.com/lmjfmqsrc/homework/blob/master/16061032.md

**Comment by 16061182** [comment]
https://github.com/16061182/Lecture/blob/master/16061182.md

**Comment by mahaoxiang822** [comment]
https://github.com/mahaoxiang822/homework_frontier_lecture/blob/master/16061097.md

**Comment by RageOvO** [comment]
https://github.com/RageOvO/Homework-buaa/blob/master/16061114.md

**Comment by Nerdary** [comment]
https://github.com/Nerdary/FrontierLectureSpring2019/blob/master/16061146.md

**Comment by mxj1606** [comment]
https://github.com/mxj1606/-/blob/master/16061127.md

**Comment by AlbertShenC** [comment]
https://github.com/AlbertShenC/FrontierLectureSpring2019/blob/master/16231247.md

**Comment by peanuTnTzz** [comment]
https://github.com/peanuTnTzz/homework/blob/master/16061140.md

**Comment by zzpp2333** [comment]
https://github.com/zzpp2333/BUAA-AI-edu/blob/master/16061121.md

**Comment by sbs384** [comment]
https://github.com/sbs384/lecture_assignment/blob/master/16061094.md

**Comment by ws-zzy** [comment]
https://github.com/ws-zzy/myblog/blob/master/posts/16061137.md

**Comment by Kevinjyp** [comment]
https://github.com/Kevinjyp/HomeWork/blob/master/16231030.md

**Comment by kf16061064** [comment]
https://github.com/kf16061064/homework/blob/master/16061064.md

**Comment by Devot1on** [comment]
https://github.com/Devot1on/ai-edu/blob/master/16061128.md

**Comment by idealee66** [comment]
https://github.com/idealee66/homework_Lecture2019/blob/master/16061077.md

**Comment by ffiamz** [comment]
https://github.com/ffiamz/lecture_2019/blob/master/16061074.md

**Comment by theloadstar** [comment]
https://github.com/theloadstar/Lecture2019/blob/master/16061133.md
>16061133

**Comment by Lemeowy** [comment]
https://github.com/Lemeowy/AI-challenge-hw/blob/master/16061195.md

**Comment by GJZhou** [comment]
https://github.com/GJZhou/Homework_lecture/blob/master/16061145.md

**Comment by Joy-ceu** [comment]
https://github.com/Joy-ceu/homework/blob/master/16061151.md

**Comment by caozuoxitong** [comment]
https://github.com/caozuoxitong/-/blob/master/16182653.md

**Comment by 17vvvvv** [comment]
https://github.com/17vvvvv/-/blob/master/16182609.md

**Comment by Dr1st** [comment]
https://github.com/Dr1st/Front_Class/blob/master/16231183.md

**Comment by eerstone** [comment]
https://github.com/eerstone/FrontierLecture2019Spring/blob/master/16061070.md

**Comment by las1374236892** [comment]
https://github.com/las1374236892/-/blob/master/16061023.md

**Comment by AyaIsLearning** [comment]
https://github.com/AyaIsLearning/BUAA-AI-EDU-HOMEWORK/blob/master/16061030.md

**Comment by 16231108** [comment]
https://github.com/16231108/jiadongwang/blob/master/16231108.md

**Comment by AndysonYs** [comment]
https://github.com/AndysonYs/homework_lecture2019/blob/master/16061067.md

**Comment by 16061036** [comment]
https://github.com/16061036/BeihangUniversity2019Spring/blob/master/16061036.md

**Comment by study0098** [comment]
https://github.com/study0098/BUAA_AI_Homework/blob/master/16061066.md

**Comment by mzymzy** [comment]
https://github.com/mzymzy/HomeWork_FrontierLecture2019Spring/blob/master/16061109.md

**Comment by jinglinyuan** [comment]
https://github.com/jinglinyuan/homework/blob/master/16061142.md

**Comment by OneIsAll980516** [comment]
https://github.com/OneIsAll980516/BeihangUniversity2019Lecture/blob/master/16061002.md

**Comment by TechpriestW** [comment]
https://github.com/TechpriestW/buaa2019LectureHomework/blob/master/16061095.md

**Comment by kazr97** [comment]
https://github.com/kazr97/homework/blob/master/16061089.md

**Comment by wyh1029** [comment]
https://github.com/wyh1029/lecture-homework/blob/master/16182672.md

**Comment by LuZZhang** [comment]
https://github.com/LuZZhang/BUAA_Frontier_Science_Lecture_Homework/blob/master/16061092.md

**Comment by cqnkjsx** [comment]
https://github.com/cqnkjsx/homework_conference/blob/master/16061171.md

**Comment by xuyibo1230** [comment]
https://github.com/xuyibo1230/assignment/blob/master/16061112.md

**Comment by neolinsu** [comment]
> **2019年春季 北航《计算机科学前沿》挑战**
> 作业要求在这里：
> https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/BeihangUniversity2019Spring
> 
> 请北航的学生们把你的作业链接 （应该指向你的 github 账户中的一个markdown 文件）回复到这个 Issue 下面即可。

https://gist.github.com/neolinsu/ce45be3fb8a39dbeaceb4f0842f09de3

**Comment by chuan1093** [comment]
https://github.com/chuan1093/homework/blob/master/16061093.md

**Comment by notstandalone** [comment]
https://github.com/notstandalone/Homework/blob/master/16061119.md

**Comment by Jackson0813** [comment]
https://github.com/Jackson0813/BUAA_Microsoft/blob/master/16061068.md

**Comment by wlof-2** [comment]
https://github.com/wlof-2/Calculator/blob/java/16061106.md

**Comment by tigerbroken** [comment]
https://github.com/tigerbroken/homework/blob/master/16231065.md

**Comment by im73** [comment]
https://github.com/im73/Homework/blob/master/16061086.md

**Comment by PaParaZz1** [comment]
https://github.com/PaParaZz1/E-challenge-homework/blob/master/16131059.md

**Comment by SASAWEN** [comment]
https://github.com/SASAWEN/Microsoft_AI-edu_homework/blob/master/16061122.md

**Comment by zbjlhjq** [comment]
> 2019年春季 北航《计算机科学前沿》挑战
> 作业要求在这里：
> https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/BeihangUniversity2019Spring
> 请北航的学生们把你的作业链接 （应该指向你的 github 账户中的一个markdown 文件）回复到这个 Issue 下面即可。

https://github.com/zbjlhjq/Homework/blob/master/16061181.md

**Comment by zbjlhjq** [comment]
https://github.com/zbjlhjq/Homework/blob/master/16061181.md

**Comment by bind-TIAN** [comment]
https://github.com/bind-TIAN/Home-work/blob/master/16182685.md

**Comment by PhoebeAbbey** [comment]
https://github.com/PhoebeAbbey/AI-assignment/blob/master/16061033.md

**Comment by sephyli** [comment]
https://github.com/sephyli/BUAACS_lecture2019/blob/master/16231031.md

**Comment by szh-bash** [comment]
https://github.com/szh-bash/Grocery/blob/master/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF%E8%AE%B2%E5%BA%A7/16061105.md

**Comment by sumingzs11** [comment]
https://github.com/sumingzs11/Master/blob/master/15005012.md

**Comment by Soengseon972** [comment]
https://github.com/Soengseon972/mywork/blob/master/16061063.md

**Comment by 16061054** [comment]
https://github.com/16061054/Microsoft/blob/master/16061054.md

**Comment by gilbert-gorshkov** [comment]
[https://github.com/gilbert-gorshkov/hello-world/blob/master/16061132.md
](url)

**Comment by Lafite-Yu** [comment]
https://raw.githubusercontent.com/Lafite-Yu/FrontierComputerScienceLecture/master/16061189.md

**Comment by 16182659** [comment]
啊

**Comment by 16182659** [comment]
https://github.com/16182659/ljh/blob/master/16182659.md

**Comment by 16182659** [comment]
https://github.com/16182659/ljh/blob/master/16182659.md

**Comment by mslichao** [comment]
#173 #179 #181 #188 #194 #195 #196 #197 #240 #243
may belong this challenge too, close them due to the wrong reply format.
