### ISSUE TITLE
2019 HUAT AI Challenge

### ISSUE THREAD

**Issue by gjy2poincare** [Microsoft/ai-edu#182]
2019年 湖北汽车工业学院《车载智能信息处理》课程作业与实战
作业要求在这里：
https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/HUAT2019Challenge
请学生们把你的作业链接 （应该指向你的github 账户中的一个markdown 文件）回复到这个 Issue 下面即可。

**Comment by Fblackp** [comment]
https://github.com/Fblackp/homework-01/blob/master/201702051.md
