### ISSUE TITLE
B-教学案例与实践/B6-神经网络基本原理简明教程

### ISSUE THREAD

**Issue by DaZiYuan** [Microsoft/ai-edu#202]
有2张图片404了。 新手看起来有点懵
https://github.com/Microsoft/ai-edu/raw/master/B-%E6%95%99%E5%AD%A6%E6%A1%88%E4%BE%8B%E4%B8%8E%E5%AE%9E%E8%B7%B5/B6-%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E5%9F%BA%E6%9C%AC%E5%8E%9F%E7%90%86%E7%AE%80%E6%98%8E%E6%95%99%E7%A8%8B/Images/8/r128-1000-1391.png

https://github.com/Microsoft/ai-edu/raw/master/B-%E6%95%99%E5%AD%A6%E6%A1%88%E4%BE%8B%E4%B8%8E%E5%AE%9E%E8%B7%B5/B6-%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E5%9F%BA%E6%9C%AC%E5%8E%9F%E7%90%86%E7%AE%80%E6%98%8E%E6%95%99%E7%A8%8B/Images/1/Linearvsactivation.png

**Comment by xiaowuhu** [comment]
fixed, please check. Thanks!
