### ISSUE TITLE
homework

### ISSUE THREAD

**Issue by bind-TIAN** [microsoft/ai-edu#243]
在人工智能发展史上，有繁荣也有低谷。并且值得注意的是，虽然发展往往带来许多负面影响，但人工智能的发展大体呈现出上升趋势，并且正在走向突破阶段。谈起人工智能，会不自觉的觉得这个名词十分的高大尚，一般人或许很难明白其内部机理。其实，人工智能的根基就在于把所有的计算、数据、云端和物联网终端的设备联系起来，搭建一个能支持智能决定的系统。这个系统对人类的活动是有益处的，譬如像智能电子设备，能够在一定程度上满足人们的精神需求。所以说人工智能并不难以想象，它就在我们身边。
还记得围棋冠军被机器人打败的例子，人工智能是如何做到复杂情况判断的呢？当机器跟人对弈围棋的时候，我们表面上看机器人是在思考如何走，其实它并不知道自己是在下棋，而是处理一些复杂的矩阵运算，达到落下一步棋的目的。至于我们还谈到的机器人可以自己跟自己对弈，提升自己的能力，也不过是进行数据的处理而已。因此，机器人通过这些不断的计算，由于处理能力之快，它所表现出来的一些行为，看起来是经过“深思熟虑”的，那么我们也就会说此时机器人它本身具有了一定的“智慧”，这些“智慧”建立在拥有复杂的运算背景下。
机器人不仅能够下围棋，甚至也能够像一个诗人一样做诗。这个是真的吗？的确如此，机器人确实会作诗，然而并不能触景生情。与其说它能够吟诗作赋倒不如讲它是单纯的把一些景物进行识别，根据其内部存储的数据，通过景物得出一些匹配词组，然后进行单纯意义上的组合而已。这样做出的诗是十分平淡无味的。要是一个普通人看到这样的诗句，没准会无法想象出当时的意境出来。因此，在这一方面机器人也是没有感情色彩的，也就是没有“智慧”的，或者说没有像人类一样的智慧。
上面的两个例子回答了关于“中文房间”的问题。也即是：智能并不是一个可计算的问题。何谓“中文房间”？普遍的解释是说让一个身处密闭房间里不懂中文的机器人处理中文问题并回答外部世界中的人给出的中文问题；而且这个机器人其实压根就不懂得中文的语义，也就是对所拿到的问题其实是一无所知的。那如果在这样的情况下，该机器人是否能够像人一样思考，也就引发了一系列争论。在这里我想说的是，即使我们在某些情况下比如下棋和作诗表面上看起来机器人可以进行“思考”，但其实它们仅仅是处理数据而已，并不就有人的意识，也就谈不上是一个完整的人，也就没有人的智慧。
人工智能是如何发展起来的呢？或者说这个发展建立的根基是怎样的呢？有没有别的方面间接影响了人工智能历史的发展？
我们出生在自然中，时刻离不开大自然。处于对自然的好奇，我们人类开始了永无止境的探索。当看到一些奇特的自然现象的时候，不由得会研究它。为了带来数据上的可靠性，开始了不断的体验和总结规律的过程。于是，一些基本的自然现象就被描述和记录了下来，并被后人引用并继续探究。其实在观察类比的过程中，发生了一些有意思的现象。比如，由于穿山甲善于打洞，“象形”的思维方式认为穿山甲有“打通”的效力，因此遇到诸如乳汁不同等情况时，穿山甲就能起作用。不过有的时候，人的眼睛会欺骗自己，所以观察并不总能解决问题，而且有些事物也是没有规律的，但是对于普遍的问题，我们可以进行总结和推广。随着不断的升华提炼，人类逐渐总结出了一系列反应该问题的公式和定理，通常这些定理也是仅仅的描述物体的客观规律而已。比如我国的数学家祖冲之，就提出了圆周率的概念，这是通过观察圆形的物体得出的结论。通过比萨斜塔自由落体运动，伽利略进一步给出真空中羽毛和钢球下落一样快的奥秘。因此，无论在什么情况下，凡事必有因果存在。
那么一个有意思的问题也就出现了，也就是在因果论背景下，三门选择问题成为了焦点。
问题的背景是这样的。有三个门，每个门后面都有奖品。其中有一个门后面的奖品是一辆汽车，而其他的两扇门后面则是一头羊。现在让参赛者随机挑选出一扇门，领走后面的奖
品。虽然参赛者并不清楚门的后面是什么，但是主持人却清楚。当参赛者挑选出其中的一扇门后，主持人就立刻给出另一扇带有羊的门，并且提问参赛者是否立刻换门。这时的参赛者到底该不该换门，来获得最终的汽车这个大奖。对此我的理解如下。首先假设参赛者已经选中了带有汽车的门，也就相当于他已经获得了最终想要得到的大奖。但是他自己此时并不知情，因为在他的印象中，这扇门后面有可能是车、有可能是羊。他此时看到了主持人开了一扇带有羊的门，那么他就会觉得此时他已经开的这扇门后面是车的概率为二分之一，那他就不会选择继续换门，因为换另一扇门其实概率也是一样的。但实际情况并不像他所想的那样，这扇门后面其实已经存在了汽车，这个汽车选择其实是他在之前主持人没开门时选择的，也就是说之前他选中汽车的概率为三分之一。那么，此刻当主持人问是否换门时，若继续换门，势必会离得不到汽车，那么此时得到汽车的概率就变为了零。因此决定他得不得到汽车的概率取决于自己的决定，但本质上他已经得到了汽车，这个概率来源于之前的概率也即是三分之一。但是如果之前这个人并没有选中汽车，而是选中了得到羊这个奖品的门，那么同样的分析，当主持人打开另一扇有羊的门的时候，这个人就立刻明白，此时这扇门为汽车的概率是二分之一。如果他此时换门，客观上来讲是必定得到汽车，但是他本人并不清楚，因此此刻对于他自己来讲，即使换了门，他得到汽车的概率依然为二分之一。因此综上所述，对于参赛者自己来讲，在两种都换门的情况下，他得到汽车的概率显然是不一样的。到底该不该换门，其实各有利弊，也就是说概率并不能真正反映客观的实在性。
我们身处人工智能的时代，利用人工智能产品来解决我们客观遇到的问题是十分有帮助的。那么将来能不能做出一个学生青睐的具有人工智能的“学习助手”出来，帮助学生们更好的解答学习上的问题。这款人工智能的构思大概是这样的：同学们遇到不会的问题，就随时随地请教“学习助手”，它甚至可以集成各个专业领域内其他学习资料，实现随时随地学习知识的数据支持。这个创意的确能解决学生遇到不会的问题。比如各种找资料而无法得到解答的困境，另外随时随地背英语单词或者回忆学过的公式定理，也可以加深学生们对知识的理解，能够帮助他们更好的利用碎片化的时间来温故知新。这个产品的核心之处在于它能够根据用户实际的需要来满足用户，其中包含了许多自学习算法和大量的数据存储；另外还具有一定的可识别能力，实现人机交互的最大满意度目标。比如当用户想学习英语的时候，用户会做出一些手势出来，那么“学习助手”识别这些手势并反馈给用户想要的结果才能真正帮助用户解答疑惑。对于自学习算法来讲，贝叶斯算法具有一定的优势。这个方法可以进行数据的分析和预测。在设计“学习助手”之前，需要进行大量关于手势信息的采集，并进行数据训练。做成之后，根据不同的手势动作，做出下一步的预测，从而让用户满意。其实这个产品是十分有市场竞争力的，原因在于我国是教育大国，家长们也普遍希望自己的孩子们能够在学习上有所突破。无论对哪一方，这款产品势必会给他们带来福音。产品在上市之前需要评估，这需要一部分志愿者参与，或者将该产品部分投放到一些学习平台，来获取客户使用过程中的一些重要数据。这些数据能够更好的帮助提升产品的质量，做出一份令消费者满意的人工智能软件。

**Comment by mslichao** [comment]
Close due to the wrong reply format.
