### ISSUE TITLE
2019 夏季清华大学实习生 Code Search Challenge

### ISSUE THREAD

**Issue by mslichao** [microsoft/ai-edu#282]
**Code Search Challenge**

详细介绍在：https://github.com/Microsoft/ai-edu/tree/master/E-Challenge/CodeSearch

请将作业链接回复到这个Issue下。

有任何疑问也可以在这个Issue下回复。

**Comment by maoyutao** [comment]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/23288182/60448248-d750df00-9c57-11e9-8552-c342f1f8924b.png">
第一周工作安排中读文章的任务说明似乎没有给出文章列表～

**Comment by maoyutao** [comment]
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/23288182/60475564-861e0b00-9caa-11e9-876b-b862183d063d.png">
这里的文章列表是不是还没有给出呀？

**Comment by mslichao** [comment]
> <img alt="image" width="1028" src="https://user-images.githubusercontent.com/23288182/60475564-861e0b00-9caa-11e9-876b-b862183d063d.png">
> 
> 这里的文章列表是不是还没有给出呀？还是就是指参考资料里的那些文章呀？

是的，是参考资料里除了VSCode Extension以外的文章。

这里描述的不清晰，我稍后改一下。

**Comment by maoyutao** [comment]
https://github.com/maoyutao/CodeSearch/blob/master/第一周学习.md

**Comment by SSRSGJYD** [comment]
https://github.com/SSRSGJYD/Code-Search

**Comment by ThuWangzw** [comment]
Questions & NABCD: https://github.com/ThuWangzw/ms-ai/blob/master/questions.md

**Comment by fengh16** [comment]
Question: https://github.com/fengh16/2019SummerIntern/blob/master/Questions.md

**Comment by beyondhtx** [comment]
https://github.com/beyondhtx/MS-SummerIntern-2019/blob/master/Questions%20and%20Surveies.md

**Comment by LebronAl** [comment]
https://github.com/LebronAl/microsoft-ai/tree/master/%E7%AC%AC%E4%B8%80%E5%91%A8%E4%BD%9C%E4%B8%9A

**Comment by xinase** [comment]
> [https://github.com/maoyutao/CodeSearch/blob/master/第一周学习.md](https://github.com/maoyutao/CodeSearch/blob/master/%E7%AC%AC%E4%B8%80%E5%91%A8%E5%AD%A6%E4%B9%A0.md)

can not open your link, could you double check or use all English in your address? thanks.

**Comment by maoyutao** [comment]
> > [https://github.com/maoyutao/CodeSearch/blob/master/第一周学习.md](https://github.com/maoyutao/CodeSearch/blob/master/%E7%AC%AC%E4%B8%80%E5%91%A8%E5%AD%A6%E4%B9%A0.md)
> 
> can not open your link, could you double check or use all English in your address? thanks.

sorry, I forgot to change the default settings. now you can open it.

**Comment by sunziping2016** [comment]
https://github.com/sunziping2016/code-search/blob/master/wk1-homework.md
孙子平
