### ISSUE TITLE
 I have a problem in B6  step2  0.4.4

### ISSUE THREAD

**Issue by yhx0105** [microsoft/ai-edu#299]
Maybe,there are some mistakes here.
`$$
{\partial J \over \partial w}=
\begin{pmatrix}
    {\partial J \over \partial z_1}{\partial z_1 \over \partial w} \\
    \\
    {\partial J \over \partial z_2}{\partial z_2 \over \partial w} \\
    \\
    {\partial J \over \partial z_3}{\partial z_3 \over \partial w} 
\end{pmatrix}
=\frac{1}{3}\begin{pmatrix}
    (z_1-y_1)x_1 \\ (z_2-y_2)x_2 \\ (z_3-y_3)x_3
\end{pmatrix}
$$
$$
=\frac{1}{3}
\begin{pmatrix}
    x_1 & x_2 & x_3
\end{pmatrix}
\begin{pmatrix}
    z_1-y_1 \\
    z_2-y_2 \\
    z_3-y_3 
\end{pmatrix} \tag{m=3}
$$
$$
=\frac{1}{m} X^T \cdot (Z-Y) \tag{4}
$$
`
matrix 1*3 multiply matrix 3*1 equals matrix 1*1 rather a matrix 3*1

**Comment by xiaowuhu** [comment]
是3行1列的结果，您指的是哪个公式？公式4和公式5的结果都是1行1列。

**Comment by xiaowuhu** [comment]
Oh, I got your point. Yes, you are right. I will remove this formular. Thanks!

**Comment by yhx0105** [comment]
谢谢------------------ 原始邮件 ------------------
发件人: "xiaowuhu"<notifications@github.com>
发送时间: 2019年7月25日(星期四) 中午12:31
收件人: "microsoft/ai-edu"<ai-edu@noreply.github.com>;
抄送: "yhx0105"<1370117133@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/ai-edu]  I have a problem in B6  step2  0.4.4 (#299)



Oh, I got your point. Yes, you are right. I will remove this formular. Thanks!
 
&mdash;
