### ISSUE TITLE
好像是一个简单的命名错误

### ISSUE THREAD

**Issue by 4mmmm** [microsoft/ai-edu#352]
我在学习B6-神经网络基本原理简明教程中Step3-LinearClassification时，在二分类结果可视化时尝试运行了一下ch06，level2的代码，结果error了，经排查后发现应该是ch06中HelperClass.NeuralNet_1_2.py中21行引用错误，原为from HelperClass.ClassifierFunction import *，实际应为from HelperClass.ClassifierFunction_1_0 import *，我在更改这个bug后成功运行了代码

**Comment by xiaowuhu** [comment]
fixed
