### ISSUE TITLE
为什么“一层神经网络中的所有神经元的激活函数必须一致”？

### ISSUE THREAD

**Issue by sjtu-liuchao** [microsoft/ai-edu#359]
Step1 01.0的小结中有“一层神经网络中的所有神经元的激活函数必须一致”，但上文中并没有出现对这条的说明，如果不一致会如何？

**Comment by yhx0105** [comment]
可能是每一层只能有一个激活函数吧

**Comment by yrpang** [comment]
是不是因为激活函数表示这个神经元的刺激阀值，要是同一层的不一样，没有意义emm（我也不太懂

**Comment by xiaowuhu** [comment]
不一样的话，输出“电平”不一致，就无法比较了。
