### ISSUE TITLE
一个Bug

### ISSUE THREAD

**Issue by yyjxx2010xyu** [microsoft/ai-edu#434]
[在ch09-NonLinearRegression的源码里](https://github.com/microsoft/ai-edu/blob/master/B-%E6%95%99%E5%AD%A6%E6%A1%88%E4%BE%8B%E4%B8%8E%E5%AE%9E%E8%B7%B5/B6-%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E5%9F%BA%E6%9C%AC%E5%8E%9F%E7%90%86%E7%AE%80%E6%98%8E%E6%95%99%E7%A8%8B/SourceCode/ch09-NonLinearRegression/Level6_TuneParams.py)
![issue](https://user-images.githubusercontent.com/5267618/69520821-8d66ed80-0f98-11ea-8749-6afdd0b4f604.png)
其中的ne和batch调用的是全局变量里，应该改为 n_hidden和batch_size。不过在因为代码里直接修改一次ne和batch就直接调用该函数，所以在原代码中没有问题.

**Comment by xiaowuhu** [comment]
fixed. Thanks!
