### ISSUE TITLE
链接有错误

### ISSUE THREAD

**Issue by Limbo-NKU** [microsoft/ai-edu#459]
具体位置：
ai-edu/A-教学课程/基于Visual_Studio_Tools_for_AI的高级机器学习课程-复旦赵卫东.md

城市声音分类和图像超分辨率案例均指向同一个项目，请检查是否出错并补充图像超分辨率案例的链接，感谢。

**Comment by xiaowuhu** [comment]
fixed

**Comment by TobeyQin** [comment]
Thank you for your feedback, help us to fix the bug. You can pull the corrected file now.
BTW, we have adjusted the resource structure several weeks ago, now it is in "E-课程集锦" instead of "A-教学课程".
