### ISSUE TITLE
基础教程 05.4 章代码小错误

### ISSUE THREAD

**Issue by purple4pur** [microsoft/ai-edu#486]
[文章传送门](https://github.com/microsoft/ai-edu/blob/master/A-%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B/A2-%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E5%9F%BA%E6%9C%AC%E5%8E%9F%E7%90%86%E7%AE%80%E6%98%8E%E6%95%99%E7%A8%8B/Step2%20-%20LinearRegression/05.4-%E8%BF%98%E5%8E%9F%E5%8F%82%E6%95%B0%E5%80%BC.md)

> 可以看到loss、w1、w2、b的值，每次跳跃都很大，怀疑是学习率过高导致的梯度下降在最优解附近徘徊。所以，我们先把超参修改一下：
> 
> ```Python
> params = HyperParameters(eta=0.01, max_epoch=50, batch_size=10, eps=1e-5)
> ```

这里的 `max_epoch` 根据上下文来看应该是 500。

**Comment by xiaowuhu** [comment]
thanks, fixing.
