### ISSUE TITLE
基础教程 06.1 章推导过程有笔误

### ISSUE THREAD

**Issue by purple4pur** [microsoft/ai-edu#487]
[文章链接](https://github.com/microsoft/ai-edu/blob/master/A-%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B/A2-%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E5%9F%BA%E6%9C%AC%E5%8E%9F%E7%90%86%E7%AE%80%E6%98%8E%E6%95%99%E7%A8%8B/Step3%20-%20LinearClassification/06.1-%E4%BA%8C%E5%88%86%E7%B1%BB%E5%87%BD%E6%95%B0.md)

> $$
> a=\frac{1}{1+e^{-(xw+b)}}
> $$
> 
> 令$z=e^{-(xw+b)}$：
> 
> $$
> a=\frac{1}{1+e^{-z}} \tag{12}
> $$

正确应为令 $z=xw+b$ 或者 $e^{-z}=e^{-(xw+b)}$~

**Comment by xiaowuhu** [comment]
Thanks. fixing it...
