### ISSUE TITLE
2020实践空间站 - NNI Student Program 2020 成果提交

### ISSUE THREAD

**Issue by kvartet** [microsoft/ai-edu#582]
本 issue 是2020实践空间站 - [NNI Student Program 2020](https://github.com/microsoft/ai-edu/tree/master/G-实践项目/NNI-Student-Program-2020) 项目成果的提交地址，请同学们把相关信息按照下面的格式回复到这个 issue 下面。

```
1. 团队名：
2. 团队人员：
3. 团队学校：
4. 任务完成情况：
5. Github Repo地址：
6. 补充信息（若有）：
```
------------
更新任务截止日期：
+ 第一轮 DDL：2021.2.7
  + Task 1、Task 2.1、Task 3.1、Task 4 启动报告
+ 第二轮 DDL：2021.3.14
  + Task 2.2、Task 3.2、Task 4 中期报告（不强制）
+ 第三轮 DDL：2021.4.4
  + Task 4 结项报告

**Comment by babyyang525** [comment]
1. 团队名：啦啦啦525
2. 团队人员：杨思慧
3. 团队学校：西安交通大学
4. 任务完成情况：Task1
5. Github Repo地址：https://github.com/babyyang525/Micro_NNI

**Comment by xmx-521** [comment]
1. 团队名：电脑一带五
2. 团队人员：徐满心、李乐天、孟繁青、尚丙奇、陈垲昕
3. 团队学校：同济大学
4. 任务完成情况：
    - [x] Task 1
    - [x] Task 2.1
    - [x] Task 3.1
    - [x] Task 4 项目启动文档
5. Github Repo地址：https://github.com/xmx-521/NNI-Student-Program-2020

**Comment by RuaYiii** [comment]
1.团队名：电脑一带五
2.团队人员：范森然、赵钰杨、石基宽
3.团队学校：北京邮电大学
4.任务完成情况:    
   - Task1      √
   - Task2.1   √
5.Github Repo地址:  https://github.com/RuaYiii/MSC-NNI-project

**Comment by Marlowe997** [comment]
团队名：Vesper
团队人员：成军玮 欧阳天昊 刘佳华 何龙
团队学校：北京邮电大学
任务完成情况：Task1, Task2.1 √
Github Repo地址：https://github.com/Marlowe997/NNI-Student-Program-2020-Vesper

**Comment by KiritakeKumi** [comment]
团队名：niconiconi
团队人员：蒲镜羽
团队学校：电子科技大学
任务完成情况：Task1,Task2.1 √
Github Repo地址：https://github.com/KiritakeKumi/MS_NNI_2020

**Comment by Garen-Wang** [comment]
1. 团队名：爱情都是卑微的
2. 团队人员：王樾
3. 团队学校：华南理工大学
4. 任务完成情况：
- [x] Task1
- [x] Task2.1
5. Github Repo地址：https://github.com/Garen-Wang/NNI-Student-Program-2020

**Comment by kb824999404** [comment]
1. 团队名：NNI Take me fly
2. 团队人员：周楷彬、庄泽杨、李俊杰
3. 团队学校：同济大学
4. 任务完成情况：
    - [x]  Task 1
    - [x]  Task 2.1
    - [x]  Task 3.1
    - [x]  Task 4 项目启动文档
5. Github Repo地址：https://github.com/kb824999404/NNI-Take-me-fly

**Comment by kb824999404** [comment]
1. 团队名：NNI Take me fly
2. 团队人员：周楷彬、庄泽杨、李俊杰
3. 团队学校：同济大学
4. 任务完成情况：
    - [x]  Task 1
    - [x]  Task 2.1
    - [x]  Task 3.1
    - [x]  Task 4 项目启动文档
5. Github Repo地址：https://github.com/kb824999404/NNI-Take-me-fly

**Comment by Concyclics** [comment]
1. 团队名：NNI-singleDog
2. 团队人员：陈涵
3. 团队学校：华南理工大学
4. 任务完成情况：
     - [x] Task 1
- [ ] Task 2
  - [x] Task 2.1
  - [ ] Task 2.2
- [ ] Task 3
  - [x] Task 3.1
  - [ ] Task 3.2
    - [ ] Task 3.2.1
    - [ ] Task 3.2.2
- [ ] Task 4
  - [x] Task 4 项目启动报告
5. Github Repo地址：https://github.com/Concyclics/NNI-singleDog
