### ISSUE TITLE
A-基础教程的文章中图片链接都挂了

### ISSUE THREAD

**Issue by 7Eric9** [microsoft/ai-edu#629]
例如:
https://aiedugithub4a2.blob.core.windows.net/a2-images/Images/2/flow1.png
在我提issue的这一刻，是加载不出来的，望及时解决，谢谢！

**Comment by uaicfs** [comment]
我也是买了书正在学习图片全都打不开，早知道都保存下，太遗憾了。

**Comment by xiaowuhu** [comment]
图片都存储在Azure上，目前只是Azure一个DNS故障，很快会恢复的。

**Comment by xiaowuhu** [comment]
recovered. 希望大家把github clone到本地，然后用VSCode浏览，效果更佳。

**Comment by xiaowuhu** [comment]
recoverd

**Comment by uaicfs** [comment]
谢谢胡老师！正在学习这本书有些概念很清楚，二分类函数logistic函数 和 sigmoid函数，解开了我对这两个函数的疑惑。
