### ISSUE TITLE
无法下载数据> 请问，数据在哪里down

### ISSUE THREAD

**Issue by SuiLiyuan** [microsoft/ai-edu#747]
> 请问，数据在哪里down

https://github.com/microsoft/ai-edu/tree/master/%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B/A2-%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E5%9F%BA%E6%9C%AC%E5%8E%9F%E7%90%86/src

_Originally posted by @xiaowuhu in https://github.com/microsoft/ai-edu/issues/415#issuecomment-915735604_

**Comment by SuiLiyuan** [comment]
运行DataDownload.py，收到异常  <urlopen error [Errno 8] nodename nor servname provided, or not known>

**Comment by xiaowuhu** [comment]
看一下 A2-神经网络基本原理/src/Data/*.py, 是各章的数据生成工具。注意把生成好的文件copy到目标章节运行即可。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年8月25日 10:47
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [microsoft/ai-edu] 无法下载数据> 请问，数据在哪里down (Issue #747)


运行DataDownload.py，收到异常 <urlopen error [Errno 8] nodename nor servname provided, or not known>

―

**Comment by SuiLiyuan** [comment]
感谢您的回复！
可以生成数据！

**Comment by xiaowuhu** [comment]
再网站上有关于数据的说明。是要运行程序，会自动生成数据。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年8月24日 21:25
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: [microsoft/ai-edu] 无法下载数据> 请问，数据在哪里down (Issue #747)


请问，数据在哪里down

https://github.com/microsoft/ai-edu/tree/master/%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B/A2-%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E5%9F%BA%E6%9C%AC%E5%8E%9F%E7%90%86/src

Originally posted by @xiaowuhu<https://github.com/xiaowuhu> in #415 (comment)<https://github.com/microsoft/ai-edu/issues/415#issuecomment-915735604>

―

**Comment by anseldu** [comment]
课件用数据又不能下载了，比如:
https://aiedugithub4a2.blob.core.windows.net/a2-data
无法打开了

**Comment by xiaowuhu** [comment]
> 课件用数据又不能下载了，比如: https://aiedugithub4a2.blob.core.windows.net/a2-data 无法打开了

仔细看一下说明 readme.md，自己运行提供的代码生成数据。
