### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/ai-edu#82]
there are 2 broken links in https://github.com/Microsoft/ai-edu/blob/master/C-%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7%E4%B8%8E%E7%8E%AF%E5%A2%83/README.md
: 

- https://github.com/Microsoft/ai-edu/blob/master/C-%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7%E4%B8%8E%E7%8E%AF%E5%A2%83/C-%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7%E4%B8%8E%E7%8E%AF%E5%A2%83/README.md
-https://github.com/Microsoft/ai-edu/blob/master/C-%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7%E4%B8%8E%E7%8E%AF%E5%A2%83/C-%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7%E4%B8%8E%E7%8E%AF%E5%A2%83/README.md

**Comment by lillzhen** [comment]
Thanks for reporting, I will fix it.

Lillian
